[package]
name = "game"
version = "0.1.0"

[dependencies]
starknet = "2.0.1"
lootitems = { path = "../loot" }
survivor = { path = "../adventurer" }
market = { path = "../market" }
obstacles = { path = "../obstacles" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts", rev = "05429e4" }

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
allowed-libfuncs = true
